<?php

function circlezon_widgets_menu() {
	$items['widgets/favorite/%'] = array(
		'title' => 'Favorite widget',
		'page callback' => 'widgets_favorite',
		'page arguments' => array(2),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function widgets_favorite($ajax){
  $card_id = $_GET['card_id'];
  $is_favorite = $_GET['is_favorite'];

  if ($is_favorite){
	  db_update('cz_card')
	    ->condition('id', $card_id)
	    ->fields(array(
	    	'widget_favorite' =>0,
	    ))
	    ->execute();

  } else {
		db_update('cz_card')
	    ->condition('id', $card_id)
	    ->fields(array(
	    	'widget_favorite' => 1,
	   	))
	    ->execute();
  }

  if ($ajax == 'ajax'){
	  $commands = array();
	  $commands[] = ajax_command_replace('.widget-favorite-' . $card_id, widgets_get_favorite_widget($card_id, !$is_favorite));
	    
	  ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
  } else {
	  return array('#markup' => 'You have favorited this card.');
  }
}

function widgets_get_favorite_widget($card_id, $is_favorite){
	$label = $is_favorite ? 'Remove from favorite' : 'Add to favorite';
	$query = array('card_id' => $card_id, 'is_favorite' => $is_favorite);
	return '<div class="widget-favorite-'.$card_id.'">'.l(t($label), 'widgets/favorite/nojs', array('attributes' => array('class' => 'use-ajax'), 'query' => $query)).'</div>';
}